#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$getShaCommand = new \App\Commands\GetShaCommand();

$script = new Application();
$script->add($getShaCommand);
$script->setDefaultCommand($getShaCommand->getName(), true);
$script->run();
